# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-18 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender', models.CharField(max_length=200)),
                ('image', models.FileField(blank=True, null=True, upload_to=b'')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=500)),
                ('safety_deposit', models.IntegerField(max_length=10)),
                ('contact_number', models.IntegerField(max_length=10)),
            ],
        ),
    ]
