# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-18 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='contact_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lender',
            name='safety_deposit',
            field=models.IntegerField(),
        ),
    ]
