# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-18 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0002_auto_20170318_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower', models.CharField(max_length=200)),
                ('sap_id', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('product_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='lender',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
