# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-19 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0003_auto_20170318_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='department',
            field=models.CharField(default='', max_length=100),
        ),
    ]
