# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-19 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0004_lender_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='sap_id',
            field=models.IntegerField(),
        ),
    ]
