# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-19 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0005_auto_20170319_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='product_id',
        ),
        migrations.AddField(
            model_name='borrower',
            name='product_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
